<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headLink()->prependStylesheet($this->assetUrl('style.css'));
$this->headScript()->prependFile($this->assetUrl('style.js'));
$this->trigger('view.layout');
$userBar = $this->userBar();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>

    <?php echo $this->htmlElement('body'); ?>
        <?php echo $userBar; ?>
        <header>
            <nav>
                <a href="<?php echo $site->url(); ?>" class="site-title">
                    <?php echo $escape($siteTitle); ?>
                </a>
                <?php echo $site->publicNav()->menu(); ?>
                <div id="search"><?php echo $this->partial('common/search-form'); ?></div>
            </nav>
        </header>
        <main class="page-content" aria-label="<?php echo $this->escapeHtml($this->translate('Content')); ?>">
            <div class="wrapper">   
                <?= $this->content; ?> 
            </div>
        </main>
    </body>
</html>
